### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by ih57452**
Import styles with `src/styles.css` instead of `angular.json` to make instructions easier.

### CODE REVIEW

**Comment by RaphaelJenni** [comment]
Hey, thanks for the PR. I thought about that as well, but `@import` has some compatibility issues with older browsers.
We should add this option, but keep the old one and probably add a third way: import via the `index.html`
Do you want to do that or should I?

**Comment by ih57452** [comment]
I can do that if you'd like.

**Comment by RaphaelJenni** [comment]
Ok, nice. And btw, I think you could have updated the PR :)

**Comment by RaphaelJenni** [comment]
Nice, thanks! Looke good.

**Pull request merged**
